### ISSUE TITLE
GenomicFeature error with mm10

### ISSUE THREAD

**Issue by MurliNair** [Bioconductor/GenomicFeatures#63]
Hi,
 
I am getting a error when I am using the makeTxDbFromUCSC() function in GenomicFeatures for mm10 genome. 
 
library(GenomicFeatures)
mm10.refseq.db <- makeTxDbFromUCSC(genome = "mm10", tablename = "knownGene")
Error in normArgTrack(track, trackids) : 'track' must be a single string
 
It does the same with the example code from help. I checked the supportedUCSCtables() function.
 
>supportedUCSCtables(genome="mm10", url=http://genome.ucsc.edu/cgi-bin/)
  tablename track subtrack
1 knownGene  <NA>     <NA>

 Kindly let me know if I missed something here. 

Sincerely, 
Murli

**Comment by hpages** [comment]
This is a known issue with `rtracklayer::trackNames()`, see https://github.com/lawremi/rtracklayer/issues/88.

Note that this also breaks **GenomicFeatures** examples on the Bioconductor daily build report in release and devel:
- https://bioconductor.org/checkResults/3.17/bioc-LATEST/GenomicFeatures/
- https://bioconductor.org/checkResults/3.18/bioc-LATEST/GenomicFeatures/

**Comment by hpages** [comment]
Heads-up: there's been some progress on this but **rtracklayer**'s issue is not fully resolved yet (despite being closed). See https://github.com/lawremi/rtracklayer/issues/88 for the details.

**Comment by hpages** [comment]
@MurliNair  This issue should be addressed in the latest version of **rtracklayer**, that is, in version **1.60.1** in BioC 3.17 (current release), and in version **1.61.1** in BioC 3.18 (current devel).

Just run `BiocManager::install()` to update all your packages to the latest version.

Please let me know if you're still having problems after the update.

Best

**Comment by MurliNair** [comment]
I ran BiocManager::install(), it gave an error while updating interp package. Then I force installed rtracklayer using BiocManager::install("rtracklayer", force=T)
I still get the same error.  When I checked the version of rtracklayer it was rtracklayer_1.54.0 using sessionInfo().
Do I need to download the specific version and install it ? Please let me know. 
Thanks a lot for your help. 
Cheers../Murli

**Comment by hpages** [comment]
You seem to be using an old version of Bioconductor (apparently BioC 3.14). This version is lagging several versions behind the current release (BioC 3.17).

Please note that old Bioconductor versions are frozen and unsupported, so **rtracklayer** will remain broken in all BioC versions prior to 3.17.

Please upgrade to BioC 3.17 to get the latest fixes. You will need to install R 4.3 for that.

Best

**Comment by MurliNair** [comment]
Thanks, I was able install it properly on my windows machine without any problem. It has only 64Gb RAM.
 I am unable to upgrade it to R4.3 on my server runs RHEL 7.9,  and on my server which runs Oracle Linux Server release 9.2.  I guess they don't have  R 4.3 version OL9.2.  Any work arounds for this? Is it possible to update the older version of the package?

**Comment by hpages** [comment]
Have you tried using the precompiled `.deb` or `.rpm` packages for R 4.3 [available on CRAN](https://cran.r-project.org/)? They should be pretty straightforward to install.

Alternatively you could install R 4.3 from source. This is very easy to do on Linux. See the ["R Installation and Administration" manual](https://cran.r-project.org/doc/manuals/r-release/R-admin.html) for how to do this.

Note that being able to install the most recent version of R is required for using Bioconductor. See https://bioconductor.org/install/#install-R
